version: 2

jobs:
  tsc:
    working_directory: ~/react-get-not-declared-props
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Install Packages
          command: yarn install
      - run:
          name: Run tsc
          command: yarn tsc
  prettier:
    working_directory: ~/react-get-not-declared-props
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Install Packages
          command: yarn install
      - run:
          name: Run prettier
          command: yarn format --list-different
  test:
    working_directory: ~/react-get-not-declared-props
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Install Packages
          command: yarn install
      - run:
          name: Run Tests & Check Coverage
          command: yarn test:coverage

  build:
    working_directory: ~/react-get-not-declared-props
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Install Packages
          command: yarn install
      - run:
          name: Build
          command: yarn build

workflows:
  version: 2

  test:
    jobs:
      - tsc
      - prettier
      - test
      - build
