version: 2

jobs:
  lint:
    working_directory: ~/react-get-not-declared-props
    docker:
      - image: circleci/node:8@sha256:b4c10bbac6e23acb34253b159db99a7e511e46c1cec51f75b89e330f1db7adb6
    steps:
      - checkout
      - run:
          name: Install Packages
          command: yarn install
      - run:
          name: Lint Code
          command: yarn run lint
  flow:
    working_directory: ~/react-get-not-declared-props
    docker:
      - image: circleci/node:8@sha256:b4c10bbac6e23acb34253b159db99a7e511e46c1cec51f75b89e330f1db7adb6
    steps:
      - checkout
      - run:
          name: Install Packages
          command: yarn install
      - run:
          name: Flow
          command: yarn run flow

  test:
    working_directory: ~/react-get-not-declared-props
    docker:
      - image: circleci/node:8@sha256:b4c10bbac6e23acb34253b159db99a7e511e46c1cec51f75b89e330f1db7adb6
    steps:
      - checkout
      - run:
          name: Install Packages
          command: yarn install
      - run:
          name: Run Tests & Check Coverage
          command: yarn run test:coverage

  build:
    working_directory: ~/react-get-not-declared-props
    docker:
      - image: circleci/node:8@sha256:b4c10bbac6e23acb34253b159db99a7e511e46c1cec51f75b89e330f1db7adb6
    steps:
      - checkout
      - run:
          name: Install Packages
          command: yarn install
      - run:
          name: Build
          command: yarn run build

workflows:
  version: 2

  test:
    jobs:
      - lint
      - flow
      - test
      - build
