version: 2

jobs:
  lint:
    working_directory: ~/react-get-not-declared-props
    docker:
      - image: circleci/node:8@sha256:fbc099fbcd9619fa6e481eba0b541cbdc2726bcb32e9cc2e5f9e47482a02e0f9
    steps:
      - checkout
      - run:
          name: Install Packages
          command: yarn install
      - run:
          name: Lint Code
          command: yarn run lint
  flow:
    working_directory: ~/react-get-not-declared-props
    docker:
      - image: circleci/node:8@sha256:fbc099fbcd9619fa6e481eba0b541cbdc2726bcb32e9cc2e5f9e47482a02e0f9
    steps:
      - checkout
      - run:
          name: Install Packages
          command: yarn install
      - run:
          name: Flow
          command: yarn run flow

  test:
    working_directory: ~/react-get-not-declared-props
    docker:
      - image: circleci/node:8@sha256:fbc099fbcd9619fa6e481eba0b541cbdc2726bcb32e9cc2e5f9e47482a02e0f9
    steps:
      - checkout
      - run:
          name: Install Packages
          command: yarn install
      - run:
          name: Run Tests & Check Coverage
          command: yarn run test:coverage

  build:
    working_directory: ~/react-get-not-declared-props
    docker:
      - image: circleci/node:8@sha256:fbc099fbcd9619fa6e481eba0b541cbdc2726bcb32e9cc2e5f9e47482a02e0f9
    steps:
      - checkout
      - run:
          name: Install Packages
          command: yarn install
      - run:
          name: Build
          command: yarn run build

workflows:
  version: 2

  test:
    jobs:
      - lint
      - flow
      - test
      - build
