version: 2

jobs:
  build:
    working_directory: ~/react-get-not-declared-props
    docker:
      - image: circleci/node:4
    steps:
      - checkout
      - run:
          name: Install packages
          command: yarn install
      - run:
          name: lint
          command: yarn run lint
