version: 2

jobs:
  build:
    working_directory: ~/react-get-not-declared-props
    docker:
      - image: circleci/node:4
    steps:
      - checkout
      - run:
          name: Install packages
          command: yarn install
  test:
    steps:
      - run:
          name: Test
          command: yarn run test:coverage
      - run:
          name: Code Coverage
          command: yarn run report-coverage

  lint:
    steps:
      - run:
        name: Lint
        command: yarn run test:coverage

workflows:
  version: 2

  test:
    jobs:
      - build
      - lint:
        requires:
         - build
      - test:
        requires:
          - build